name: diane
services:
  controller:
    build: 
      context: ./controller
    volumes:
      - ../controller:/app:ro
    networks:
      VPNet:
        ipv4_address: 172.19.0.32
    restart: unless-stopped
  ollama:
    image: ollama/ollama
    networks:
      VPNet:
        ipv4_address: 172.19.0.33
    volumes:
      - ./ollama:/root/.ollama
    restart: unless-stopped
    environment:
      OLLAMA_HOST: "0.0.0.0:80"
  tts:
    build:
      context: ./tts
    networks:
      VPNet:
        ipv4_address: 172.19.0.34
    restart: unless-stopped
  # llama2:
  #   build: 
  #     context: ./llama2
  #   networks:
  #     VPNet:
  #       ipv4_address: 172.19.0.50
  #   restart: unless-stopped
  # fast-llama:
  #   build: 
  #     context: ./fast-llama
  #   networks:
  #     VPNet:
  #       ipv4_address: 172.19.0.50
  #   restart: unless-stopped
  #   volumes:
  #     - ../models:/models:ro
  
networks:
  VPNet:
    name: VPNet
    external: true
