name: diane
services:
  tts:
    build: 
      context: ./tts
    networks:
      VPNet:
        ipv4_address: 172.19.0.51
    restart: unless-stopped
  ollama:
    image: ollama/ollama
    networks:
      VPNet:
        ipv4_address: 172.19.0.50
    volumes:
      - ./ollama:/root/.ollama
    restart: unless-stopped
    environment:
      OLLAMA_HOST: "127.0.0.1:80"
  # llama2:
  #   build: 
  #     context: ./llama2
  #   networks:
  #     VPNet:
  #       ipv4_address: 172.19.0.50
  #   restart: unless-stopped
  # fast-llama:
  #   build: 
  #     context: ./fast-llama
  #   networks:
  #     VPNet:
  #       ipv4_address: 172.19.0.50
  #   restart: unless-stopped
  #   volumes:
  #     - ../models:/models:ro
  
networks:
  VPNet:
    name: VPNet
    external: true
